### PR TITLE
project change to react app

### PR DESCRIPTION
**Pull request by E-fais**
## Features Implemented
<ul>
<li>Navbar created </li>
<li>React router dom installed and set different routes </li>
<li>Home page completed</li>
<li>Docs page completed</li>
<li>Contributing page completed</li>
<li>Footer added </li>
</ul>

###  Note : 
I have used the same content and style of the original project. Just changed the project to react app.
Add and View project page and firebase config is not done.

### CODE REVIEW

**Comment by E-fais** [comment]
This will resolve issue #39

**Review by lewisushindi — COMMENTED** [review]
looks fine  .

**Comment by lewisushindi** [comment]
@E-fais what's your opinion on this ? should i merge the pull request or wait for the remaining files to be created then ill merge later on when all the files have been created ?

**Comment by munnokd** [comment]
@lewisushindi  you can merge this pull request so I can use this code and make next remaining pages.

**Comment by E-fais** [comment]
> @E-fais what's your opinion on this ? should i merge the pull request or wait for the remaining files to be created then ill merge later on when all the files have been created ?

Please do merge, i have already created necessary files. Mr @munnokd can add some additional codes and integrate firebase. 
Thanks.

**Comment by lewisushindi** [comment]
Done . Thank you @E-fais  for your contribution . Looking forward to working with you again !

**Comment by E-fais** [comment]
Thank you for accepting my PR . Love to work with you in future

**Pull request merged**
